### ISSUE TITLE
Add image preview in translations autocomplete

### ISSUE THREAD

**Issue by Sinled** [PazzaVlad/alfred-lingualeo#1]
Cпасибо за аддон, только хотел написать, но нашелся уже готовый :+1: 

В браузерном аддоне lingualeo умеет показывать превью картинки перевода, было круто если бы этот плагин для альфреда тоже это умел. 

Как я понимаю альфред не умеет показывать картинки из веба, может есть возможность как то асинхронно загружать эти картинки и подставлять в автокомплит? 

В питоне к сожалению не силен, не уверен что смогу это сделать сам.

**Comment by nanodracula** [comment]
Рад что кому-то это еще пригодилось :)

Асинхронно выйдет ли. Чтоб начались отображаться результаты, нужно отдать уже готовый xml с путями к локальным картинкам. И если их не будет к моменту отдачи результатов, то ничего отображаться не будет (насколько я понял). Хотя будет время поищу информацию по этому поводу, пока еще не особо разбирался в api альфреда.

**Comment by Sinled** [comment]
на скорую руку накидал такое решение

``` py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import urllib
import urllib2
import json
import feedback


def translate_text(query, icons=False):
    # Translate word and output it to XML parser fro Alfred
    url = "http://api.lingualeo.com/gettranslates?word=" + query
    img_base = "img.png"
    try:
        response = urllib.urlopen(url)
        data = json.loads(response.read())
        output = data["translate"]
        sorted_output = sorted(output, key=lambda student: int(student['votes']), reverse=True)
        fb = feedback.Feedback()

        for idx, item in enumerate(sorted_output):
            translation = item["value"]
            popularity = str(item["votes"])
            arguments = query+"||"+str(item["id"])
            img_path = item["pic_url"]

            if icons and img_path:
                icon = str(idx) + img_base
                urllib.urlretrieve(img_path, icon)
            else:
                icon = "icon.png"

            fb.add_item(title=translation, subtitle=popularity, arg=arguments, icon=icon)
        return fb
    except Exception as e:
        return e

```

вроде работает, подтупливает правда, но в целом приемлемо

**Comment by nanodracula** [comment]
у меня заметно подтупливает. сам api лигвы иногда тупит, а время ответа из cloudfront.net где картинки часто просто ужасное) 
да и, в принципе, зачем картинки в результатах, главное что в словаре на сайте картинка автоматом добавится. 
можешь форкнуть, но тогда лучше сделать для картинок папку и очищать ее раз в неделю\месяц, а то со временем там будет тысячи фоток)
