### ISSUE TITLE
Ru2En

### ISSUE THREAD

**Issue by vvscode** [PazzaVlad/alfred-lingualeo#2]
Можно добавить функционал с русского на английский?

**Comment by nanodracula** [comment]
API Lingualeo вроде не поддерживает обратный перевод. Сейчас нету времени реализовать это через сторонний сервис, возможно после НГ что то придумаю. PR - приветствуются :)

**Comment by vvscode** [comment]
`
curl 'https://lingualeo.com/translate.php?q=%D0%BC%D0%B0%D0%BB%D1%8B%D1%88&from=&source=ru&target=en' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: https://lingualeo.com/ru/glossary/learn/dictionary' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: lingualeouid=xxxx; optimizelyEndUserId=xxxxx; v_cnt=1; lang=ru; iface=ru; userid=258437; _ym_uid=xxxx; mobilePanelChecked=1; servid=xxx; AWSELB=xxxx; browser-plugins-msg-hide=1; daily_notification=1; _ym_isad=1; remember=xxxx; optimizelySegments=%7B%221027890468%22%3A%22direct%22%2C%221036670278%22%3A%22gc%22%2C%221037430770%22%3A%22false%22%7D; optimizelyBuckets=%7B%7D; _gat=1; browser-plugins-msg-start-show=1; tmr_detect=1%7C1513159793162; __asc=xxxxx; __auc=xxxxx; _ga=GA1.2.247825888.1512541662; _gid=GA1.2.1996156477.1513148039; _ym_visorc_837359=w' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed
`

**Comment by vvscode** [comment]
если кто-то возьмется делать 

сам тоже постараюсь посмотреть

с большего вопросы как и куда это интегрировать с alfred - запрос выше возвращает один перевод ( а не список ), так что саму функцию перевода я осилил - а дальше пока не смог )
